---
abstract: 'rest backend for ShardedKV'
author:
  - 'Andrea Guzzo <xant@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ShardedKV-Storage-Rest
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: '0'
  Net::HTTP: '0'
  ShardedKV: '0'
  Socket: '0'
  Test::HTTP::Server: '0'
  Test::More: '0'
  URI: '0'
version: '0.7'
